import day23 from '../src/days/day23';

const sample = `..............
..............
.......#......
.....###.#....
...#...#.#....
....#...##....
...#.###......
...##.#.##....
....#..#......
..............
..............
..............`;

describe('day 23', () => {
  test('sample data', () => {
    const board = day23.parse(sample);
    expect(day23.part1(board)).toEqual(110);
    expect(day23.part2(board)).toEqual(20);
  });
});
